### ISSUE TITLE
how to stream video 

### ISSUE THREAD

**Issue by farzad-kafami** [milg0/onvif-java-lib#10]
hi
I download and run this library code 
I try to get stream uri's
`cam.getMedia().getHTTPStreamUri(p.getToken());`
`cam.getMedia().getTCPStreamUri(p.getToken());`
`cam.getMedia().getUDPStreamUri(p.getToken())`
and get this output
> http://172.22.150.32:80/profile1/media.smp
rtsp://172.22.150.32:554/onvif/profile1/media.smp
rtsp://172.22.150.32:554/onvif/profile1/media.smp

now I don't know how to get video stream from camera (I want Save or Transfer)
I googled java rtsp client but cant find any useful code or library
can you help me

**Comment by milg0** [comment]
That is no issue of this library, sorry.
