### ISSUE TITLE
<env:Reason><env:Text xml:lang="en">Optional Action Not Implemented</env:Text>

### ISSUE THREAD

**Issue by trendtao** [milg0/onvif-java-lib#17]
I try it code, and Response SOAP Message (GetNodeResponse): 
<env:Reason><env:Text xml:lang="en">Optional Action Not Implemented</env:Text>
please tell me why is that?
Thanks

**Comment by milg0** [comment]
The action you are trying to use has not been implemented by the maker of your NVT. So you cannot use it.
