### ISSUE TITLE
POM declaration

### ISSUE THREAD

**Issue by Arcens** [milg0/onvif-java-lib#24]
Hello, 
Firstly, thank you for this library. 
I have tried to add it to my project with my local repository maven, but when I try to use it in my project, but impossible to import all classes like OnvifDevice, etc. 
![prob1](https://user-images.githubusercontent.com/20928146/97877075-f7e1eb00-1d1c-11eb-93d7-88a7d6194705.png)

However, the library is well present in the m2/repositoty/de/onvif/onfif/1.0/onvif.jar.  
![prob3](https://user-images.githubusercontent.com/20928146/97877097-003a2600-1d1d-11eb-9274-9e3b0e88024b.png)

And I have declared it in my pom.xml
![prob2](https://user-images.githubusercontent.com/20928146/97877154-134cf600-1d1d-11eb-9ac8-67387a6ff0fa.png)

Do you have an idea? 

Thank you for your support

**Comment by milg0** [comment]
I do not support Maven, please search for a resolution on your own.
