### ISSUE TITLE
Unusually long time taken to provide required information ("No connection to camera, please try again.") if device unavailable

### ISSUE THREAD

**Issue by soumya1986** [milg0/onvif-java-lib#5]
There is a method named isOnline in class de.onvif.soap.OnvifDevice.
    private boolean isOnline() {
        // without port
        if (!HOST_IP.contains(":")) {
            System.out.println("Without Port");
            try {
                InetAddress.getByName(HOST_IP).isReachable(7500);
            }
            catch (IOException e) {
                return false;
            }
        }

There needs to be a return statement here only because IOException is not thrown here and the method returns true even if the onvif device is unavailable

A way to rectify would be to add a return keyword before the line like 
return InetAddress.getByName(HOST_IP).isReachable(7500);

Now it works fine

**Comment by milg0** [comment]
You changed the source code. In the original code there is a "return true;" at the end of the function. But I may be more readable if I add the return statement there.

**Comment by soumya1986** [comment]
Yeah, there is a return true at the end. I feel that is the problem.
If the HOST_IP is unreachable, then the line  "InetAddress.getByName(HOST_IP).isReachable(7500);" does not throw an IO Exception and the function returns true (as it is the last line). 
As a result the function returns true even if the host is not reachable which originally should have returned false.  This is creating the problem.

**Comment by milg0** [comment]
Ah, yeah, you're right. Thank you, it's fixed now.
